[package]
name = "tmux-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fzf-wrapped = "0.1.3"
itertools = "0.12.0"
simple-home-dir = "0.2.0"
tmux_interface = "0.3.1"
